idf_component_register(
    SRCS
        "main.c"
        "wifi_manager.c"
        "uart_handler.c"
        "nvs_config.c"
        "crash_guard.c"
        "captive_portal.c"
        "file_server.c"
        "control_server.c"
        "log_ring.c"
        "miner_link.c"
        "ota_miner.c"
        "ota_service.c"
        "mule_task.c"
    INCLUDE_DIRS "."
    REQUIRES
        esp_wifi
        esp_http_server
        nvs_flash
        driver
        json
        lwip
        mdns
        app_update
        esp_http_client
        esp-tls
    PRIV_REQUIRES
        mbedtls
        esp_timer
)
